Pipeline fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,8 @@
 name: Trigger-Azure-Pipeline
 on:
-  push:
+  pull_request:
+    types: [closed]
+  status:
     branches:
       - development
       - master
@@ -18,25 +20,27 @@ jobs:
         AZURE_DEVOPS_PROJECT: 'powerbi'
         AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
       run: |
-        if [[ "${{ github.ref }}" == "master" ]]; then
-            AZURE_DEVOPS_PIPELINE_ID="1"
+        if (${{ github.event_name}} == 'pull_request' && ${{ github.event.action}} == 'closed' && ${{ github.event.pull_request.merged}} == true) then
+          if [[ "${{ github.ref }}" == "master" ]]; then
+              AZURE_DEVOPS_PIPELINE_ID="1"
           elif [[ "${{ github.ref }}" == "development" ]]; then
-            AZURE_DEVOPS_PIPELINE_ID="3"
+              AZURE_DEVOPS_PIPELINE_ID="3"
           else
-            AZURE_DEVOPS_PIPELINE_ID="4"
+              AZURE_DEVOPS_PIPELINE_ID="4"
           fi
-        pipeline_url="https://dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_apis/pipelines/$AZURE_DEVOPS_PIPELINE_ID/runs?api-version=6.0-preview.1"
-        
-        echo "Triggering Azure Pipeline Only Master branch: $pipeline_url from GitHub Actions"
-        
-        response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
-          -H "Content-Type: application/json" \
-          -H "Authorization: Basic $(echo -n ":$AZURE_DEVOPS_PAT" | base64)" \
-          $pipeline_url)
+          pipeline_url="https://dev.azure.com/$AZURE_DEVOPS_ORG/$AZURE_DEVOPS_PROJECT/_apis/pipelines/$AZURE_DEVOPS_PIPELINE_ID/runs?api-version=6.0-preview.1"
+          
+          echo "Triggering Azure Pipeline Only Master branch: $pipeline_url from GitHub Actions"
+          
+          response=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Basic $(echo -n ":$AZURE_DEVOPS_PAT" | base64)" \
+            $pipeline_url)
 
-        if [ $response -ne 201 ]; then
-          echo "Failed to trigger Azure Pipeline. HTTP status code: $response"
-          exit 1
-        else
-          echo "Successfully triggered Azure Pipeline $AZURE_DEVOPS_PIPELINE_ID"
+          if [ $response -ne 201 ]; then
+            echo "Failed to trigger Azure Pipeline. HTTP status code: $response"
+            exit 1
+          else
+            echo "Successfully triggered Azure Pipeline $AZURE_DEVOPS_PIPELINE_ID"
+          fi
         fi
